import csv
import importlib
import json
import os
import sys
import termios
import threading
import traceback
import tty
from pathlib import Path
from PIL import Image, UnidentifiedImageError
from termcolor import colored


_CONF: dict[str, object] = {}
_LOCK = threading.Lock()


def _import_from(module_name, entry):
    module = importlib.import_module(module_name)
    return getattr(module, entry)


def get_conf(entry):
    if entry in _CONF:
        return _CONF[entry]

    with _LOCK:
        if entry in _CONF:
            return _CONF[entry]

        try:
            value = _import_from("config", entry)
        except (ModuleNotFoundError, AttributeError) as e:
            try:
                value = _import_from("defaults", entry)
            except AttributeError:
                # config_missing = type(e) == ModuleNotFoundError
                raise ImportError(
                    f'missing config entry "{entry}" has no default value. '
                    'Please add it in the config.py file!') from e

        _CONF[entry] = value
        return value


def find_images(path, max_depth=None):
    """Recursively find all images in path.

    Function generated by AI and verified by human.
    """
    root = Path(path)
    images = []
    root_depth = len(root.resolve().parts)
    for p in root.rglob('*'):
        try:
            if not p.is_file():
                continue
        except PermissionError:
            continue
        # skip files below max depth
        if max_depth is not None:
            if len(p.resolve().parts) - root_depth > max_depth:
                continue
        try:
            with Image.open(p) as img:
                img.verify()  # verify integrity without fully decoding
            images.append(str(p))
        except (UnidentifiedImageError, OSError):
            continue
    return images


def gather_images(paths, max_depth=None):
    images = set()
    for path in paths:
        if os.path.isdir(path):
            images.update(find_images(os.path.abspath(path), max_depth=max_depth))
        elif os.path.isfile(path):
            images.add(os.path.abspath(path))
        else:
            images.add(os.path.abspath(path))
            continue
    return list(images)


def unify_paths(base_path, paths):
    """Make every path in paths relative to `base_path`.

    If `base_path` is "auto", use the longest common prefixpath as base. If
    `base_path` is `None`, output only the file names, raising a `ValueError`
    if they are not unique. No checks are performed for whether files exist!

    In any case, return a tuple of the chosen `base_path` and the files names.
    """
    if base_path is None:
        files = [os.path.basename(path) for path in paths]
        # check for duplicates
        for i, f in enumerate(files):
            if f in files[i+1:]:
                j = files[i+1:].index(f)
                raise ValueError(
                    f'Ambiguous (duplicate) filename "{f}" in inputs. '
                    'Please include a relative path with the --base-path flag '
                    'to disambiguate or rename the file.'
                    '\n\n'
                    f'Conflicting files: "{paths[i]}" and "{paths[j]}"'
                )
    else:
        if base_path == "auto":
            base_path = os.path.commonpath(paths)
            if not os.path.isdir(base_path):
                base_path = os.path.dirname(base_path)

        base_path = os.path.normpath(base_path)
        if base_path == "/":
            files = [os.path.abspath(path) for path in paths]
        else:
            files = [os.path.relpath(path, base_path) for path in paths]
    return base_path, files


def input_char(prompt):
    fd = sys.stdin.fileno()
    old = termios.tcgetattr(fd)
    print(prompt, end="", flush=True)
    ch = ""
    try:
        tty.setraw(fd)
        ch = sys.stdin.read(1)
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, old)
    print(ch)
    return ch


def check_file_writeable(path, overwrite=False):
    """Check whether file is writeable.

    The `overwrite` argument must either be a `bool` or the literal `"ask"`. If
    `overwrite` is `"ask"` and the file exists, query the user whether to (try
    to) overwrite the file.

    Note that this function actually opens and truncates the file if it is set
    to overwrite. Nonetheless, no guarantees can be made about the writeability
    of the underlying file at any point. Use this function as a user-friendly
    way to catch errors early, in combination with fail-safe error handling.
    """
    if not isinstance(overwrite, bool) and overwrite != "ask":
        raise TypeError(
            f'argument 2 must be a bool or "ask", not {type(overwrite)}')
    try:
        open(path, mode='x').close()  # noqa: R1732
        return True
    except FileExistsError:
        if overwrite != "ask":
            return overwrite
        response = input_char(
            f'file "{path}" already exists. Overwrite? [y/N]: ')
        if response == "y":
            open(path, mode='w').close()  # noqa: R1732
            return True
        else:
            return False


def parse_image_dataset(output_file, image_paths, output_format, parse_func, *,
                        overwrite="ask", warn_threshold=None):
    if not check_file_writeable(output_file, overwrite=overwrite):
        print(f'user does not want to overwrite output file "{output_file}", '
              'aborting.')
        sys.exit(1)

    results = []
    failed = []
    warn_threshold = warn_threshold or get_conf("IMAGE_WARNING_THRESHOLD")
    try:
        for name, path in image_paths:
            try:
                image = Image.open(path)
                results.append({"file": name} | parse_func(image, path=path))
            except (FileNotFoundError, UnidentifiedImageError) as e:
                failed += [path]
                if warn_threshold is None or len(failed) <= warn_threshold:
                    print(colored("warning", "yellow")        + ": " +
                          colored(type(e).__name__, "yellow") + ": " +
                          str(e),
                          file=sys.stderr)
                    # stop printing after a certain number of warnings
                    if len(failed) == warn_threshold:
                        print(colored("warning threshold reached, suppressing "
                                      "further warnings!", "red"),
                              file=sys.stderr)
    except Exception as e:
        print(colored("error", "red") + " during processing: " +
              colored(type(e).__name__, "red")          + ": " +
              str(e),
              file=sys.stderr)
        print(traceback.format_exc())
        # raise
    finally:
        _summarize_results(
            len(image_paths), len(results), len(failed))

        if len(results) < 1:
            print("no data to write, all done.")
            sys.exit(0)

        # write data
        if output_format == "csv":
            with open(output_file, mode='w', newline='') as w:
                writer = csv.DictWriter(w, results[0].keys())
                writer.writeheader()
                writer.writerows(results)
        elif output_format == "json":
            with open(output_file, mode='w', newline='') as w:
                json.dump(results, w)

        print("wrote to output file " + colored(output_file, "green")
              + ". All done!")


def _debug_print_value(name, value):
    print(colored(name, "blue"), end=": ")
    print(value)
    print()


def _summarize_results(num_images, num_succeded, num_failed):
    # summarize stats
    print()
    if num_succeded > 0:
        print("successfully parsed "
              + colored(str(num_succeded) + " image(s)", "green") + ".")
    num_missing = num_images - num_succeded
    if num_missing > 0:
        print("during image processing,", end="")
        if num_failed > 0:
            print(colored(f" {num_failed} error(s) occured", "yellow"), end="")
        if num_failed > 0 and num_missing > num_failed:  # noqa: R1716
            print(" and", end="")
        if num_missing > num_failed:
            print(colored(f" {num_missing - num_failed} image(s) were skipped "
                          "due to an exception", "red"), end="")
        print(".")


def read_grounding_data(grounding_file):
    if grounding_file.endswith(".csv"):
        with open(grounding_file, "r") as r:
            reader = csv.DictReader(r)
            return list(reader)
    elif grounding_file.endswith(".json"):
        with open(grounding_file, "r") as r:
            return json.load(r)


def parse_grounding_data(grounding_raw):
    grounding_data = {}
    for grounding in grounding_raw:
        filename = grounding.pop("file")
        grounding_data[filename] = list(grounding.values())
    return grounding_data
